In [23]:
import sys
print(sys.executable)

c:\Users\vaibh\anaconda3\python.exe

In [24]:
import pandas as pd
from sqlalchemy import create_engine

In [25]:
engine = create_engine(
    "postgresql://postgres:root@localhost:5432/ecommerce_analytics"
)

In [26]:
orders = pd.read_sql("SELECT * FROM fact_orders;", engine)

In [27]:
orders = orders[orders["order_status"] == "delivered"]

In [28]:
orders["order_purchase_timestamp"] = pd.to_datetime(orders["order_purchase_timestamp"])

In [29]:
snapshot_date = orders["order_purchase_timestamp"].max()
print(f'Snapshot Date: {snapshot_date}')

Snapshot Date: 2018-08-29 15:00:37

In [30]:
customers = pd.read_sql("SELECT customer_id, customer_unique_id FROM dim_customers;", engine)
orders = orders.merge(customers, on="customer_id", how="left")

In [31]:
rfm = orders.groupby("customer_unique_id").agg({
    "order_purchase_timestamp": lambda x: (snapshot_date - x.max()).days,
    "order_id": "count"
})

In [32]:
rfm.columns = ["recency", "frequency"]
rfm.head()

                                  recency  frequency
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      111          1
0000b849f77a49e4a4ce2b2a4ca5be3f      114          1
0000f46a3911fa3c0805444483337064      536          1
0000f6ccb0745a6a4b88665a16c9f078      320          1
0004aac84e0df4da2b147fca70cf8255      287          1

In [33]:
order_items = pd.read_sql("SELECT * FROM fact_order_items;", engine)
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [34]:
order_value = order_items.groupby("order_id")["price"].sum().reset_index()
order_value.head()

                           order_id   price
0  00010242fe8c5a6d1ba2dd792cb16214   58.90
1  00018f77f2f0320c557190d7a144bdd3  239.90
2  000229ec398224ef6ca0657da4fc703e  199.00
3  00024acbcdf0a6daa1e931b038114c75   12.99
4  00042b26cf59d7ce69dfabb4e55b4fd9  199.90

In [35]:
orders = orders.merge(order_value, on="order_id")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,price
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,29.99
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,118.70
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,159.90
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,45.00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,19.90

In [36]:
rfm = orders.groupby("customer_unique_id").agg({
    "order_purchase_timestamp": lambda x: (snapshot_date - x.max()).days,
    "order_id": "nunique",
    "price": "sum"
})

In [37]:
rfm.columns = ["recency", "frequency", "monetary"]
rfm.head()

                                  recency  frequency  monetary
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      111          1    129.90
0000b849f77a49e4a4ce2b2a4ca5be3f      114          1     18.90
0000f46a3911fa3c0805444483337064      536          1     69.00
0000f6ccb0745a6a4b88665a16c9f078      320          1     25.99
0004aac84e0df4da2b147fca70cf8255      287          1    180.00

In [38]:
rfm["r_score"] = pd.qcut(rfm["recency"], 5, labels=[5,4,3,2,1])
rfm["f_score"] = pd.qcut(rfm["frequency"].rank(method="first"), 5, labels=[1,2,3,4,5])
rfm["m_score"] = pd.qcut(rfm["monetary"], 5, labels=[1,2,3,4,5])

rfm["r_score"] = rfm["r_score"].astype(int)
rfm["f_score"] = rfm["f_score"].astype(int)
rfm["m_score"] = rfm["m_score"].astype(int)

In [39]:
rfm["rfm_score"] = (
    rfm["r_score"].astype(str) +
    rfm["f_score"].astype(str) +
    rfm["m_score"].astype(str)
)

In [40]:
def segment_customer(row):
    r = row["r_score"]
    f = row["f_score"]
    if r >= 4 and f >= 4:
        return "Champions"
    elif f >= 4:
        return "Loyal Customers"
    elif r >= 3:
        return "Potential Loyalists"
    elif r == 2:
        return "At Risk"
    else:
        return "Lost"

rfm["segment"] = rfm.apply(segment_customer, axis=1)
rfm.head(2)

,recency,frequency,monetary,r_score,f_score,m_score,rfm_score,segment
customer_unique_id,,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,111,1,129.9,4,1,4,414,Potential Loyalists
0000b849f77a49e4a4ce2b2a4ca5be3f,114,1,18.9,4,1,1,411,Potential Loyalists

In [41]:
rfm.to_csv("rfm_segments.csv")

In [42]:
segment_summary = rfm.groupby("segment").agg(
    customers=("segment", "count"),
    revenue=("monetary", "sum"),
    avg_customer_value=("monetary", "mean")
)
segment_summary = segment_summary.sort_values("revenue", ascending=False)
segment_summary

                     customers     revenue  avg_customer_value
segment
Potential Loyalists      33602  4608965.28          137.163421
Loyal Customers          22382  3211253.51          143.474824
Champions                14961  2255504.32          150.758928
At Risk                  11150  1597486.00          143.272287
Lost                     11263  1548289.00          137.466838

In [43]:
segment_summary.to_csv("customer_segment_summary.csv")

In [44]:
rfm["segment"].value_counts()

segment
Potential Loyalists    33602
Loyal Customers        22382
Champions              14961
Lost                   11263
At Risk                11150
Name: count, dtype: int64